// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeaRFj8MfcmnNiImnIHaKRAvd86rN0Oso',
    appId: '1:987230211223:web:28d37fbae791943ac7add2',
    messagingSenderId: '987230211223',
    projectId: 'vampir-koylu2',
    authDomain: 'vampir-koylu2.firebaseapp.com',
    storageBucket: 'vampir-koylu2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEX1WsdSIIQ5MAOyfKLSp-JrCwuQRyb2o',
    appId: '1:987230211223:android:522c360d81f5c9b0c7add2',
    messagingSenderId: '987230211223',
    projectId: 'vampir-koylu2',
    storageBucket: 'vampir-koylu2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7IT9dXU9AQ9Bvc_LuSSXJqcRAwBKDAk',
    appId: '1:987230211223:ios:07378a7b40da14bfc7add2',
    messagingSenderId: '987230211223',
    projectId: 'vampir-koylu2',
    storageBucket: 'vampir-koylu2.firebasestorage.app',
    iosBundleId: 'com.example.vampirKoylu',
  );
}
