/// A single Tabu card: the word to describe + the forbidden ("taboo") words
/// the describer may not say.
class TabuCard {
  final String word;
  final List<String> forbidden;
  const TabuCard(this.word, this.forbidden);
}

/// A themed group of cards (gartic.io style). Players pick one or more
/// categories in the lobby; the match deck is the union of their cards.
class TabuCategory {
  final String id;
  final String name;
  final String emoji;
  final List<TabuCard> cards;
  const TabuCategory({
    required this.id,
    required this.name,
    required this.emoji,
    required this.cards,
  });
}

/// All available categories. Add a new [TabuCategory] here to expand the
/// game — the lobby picker and deck builder pick it up automatically; no
/// other file needs to change.
const tabuCategories = <TabuCategory>[
  TabuCategory(
    id: 'genel',
    name: 'Genel',
    emoji: '🌐',
    cards: _genelCards,
  ),
  TabuCategory(
    id: 'spor',
    name: 'Spor',
    emoji: '⚽',
    cards: _sporCards,
  ),
  TabuCategory(
    id: 'muzik',
    name: 'Müzik',
    emoji: '🎵',
    cards: _muzikCards,
  ),
  TabuCategory(
    id: 'cografya',
    name: 'Coğrafya',
    emoji: '🗺️',
    cards: _cografyaCards,
  ),
  TabuCategory(
    id: 'basit',
    name: 'Basit',
    emoji: '🧒',
    cards: _basitCards,
  ),
  TabuCategory(
    id: 'edebiyat',
    name: 'Edebiyat',
    emoji: '📚',
    cards: _edebiyatCards,
  ),
  TabuCategory(
    id: 'unluler',
    name: 'Ünlüler',
    emoji: '🌟',
    cards: _unlulerCards,
  ),
];

/// Builds a match deck from the selected category ids. Unknown ids are
/// ignored; if nothing valid is selected it falls back to "Genel".
List<TabuCard> buildDeck(List<String> categoryIds) {
  final cards = <TabuCard>[];
  for (final cat in tabuCategories) {
    if (categoryIds.contains(cat.id)) cards.addAll(cat.cards);
  }
  if (cards.isEmpty) {
    cards.addAll(tabuCategories.first.cards);
  }
  return cards;
}

const _genelCards = <TabuCard>[
  TabuCard('Televizyon', ['Ekran', 'İzlemek', 'Kanal', 'Kumanda', 'Dizi']),
  TabuCard('Futbol', ['Top', 'Maç', 'Gol', 'Saha', 'Takım']),
  TabuCard('Kahve', ['İçecek', 'Sıcak', 'Fincan', 'Kafein', 'Türk']),
  TabuCard('Deniz', ['Su', 'Mavi', 'Tuz', 'Dalga', 'Plaj']),
  TabuCard('Okul', ['Öğrenci', 'Öğretmen', 'Ders', 'Sınıf', 'Eğitim']),
  TabuCard('Telefon', ['Aramak', 'Mobil', 'Ekran', 'Mesaj', 'Cep']),
  TabuCard('Doktor', ['Hasta', 'Hastane', 'Sağlık', 'Muayene', 'Reçete']),
  TabuCard('Kitap', ['Okumak', 'Sayfa', 'Yazar', 'Roman', 'Kütüphane']),
  TabuCard('Güneş', ['Sıcak', 'Işık', 'Gökyüzü', 'Sarı', 'Yaz']),
  TabuCard('Araba', ['Sürmek', 'Tekerlek', 'Yol', 'Motor', 'Volan']),
  TabuCard('Pizza', ['Hamur', 'Peynir', 'İtalyan', 'Dilim', 'Fırın']),
  TabuCard('Kedi', ['Hayvan', 'Miyav', 'Pati', 'Evcil', 'Fare']),
  TabuCard('Müzik', ['Şarkı', 'Dinlemek', 'Nota', 'Ses', 'Enstrüman']),
  TabuCard('Uçak', ['Uçmak', 'Havaalanı', 'Pilot', 'Gökyüzü', 'Kanat']),
  TabuCard('Para', ['Cüzdan', 'Banka', 'Alışveriş', 'Kağıt', 'Madeni']),
  TabuCard('Bilgisayar', ['Klavye', 'Ekran', 'Fare', 'İnternet', 'Yazılım']),
  TabuCard('Düğün', ['Gelin', 'Damat', 'Evlilik', 'Salon', 'Davet']),
  TabuCard('Yağmur', ['Su', 'Bulut', 'Şemsiye', 'Islak', 'Damla']),
  TabuCard('Çikolata', ['Tatlı', 'Kakao', 'Şeker', 'Kahverengi', 'Bar']),
  TabuCard('Aslan', ['Hayvan', 'Vahşi', 'Kral', 'Yele', 'Kükremek']),
  TabuCard('Sinema', ['Film', 'Bilet', 'Perde', 'Salon', 'Patlamış']),
  TabuCard('Çay', ['İçecek', 'Bardak', 'Demlemek', 'Sıcak', 'Türk']),
  TabuCard('Bayram', ['Tatil', 'Şeker', 'Ziyaret', 'Kutlama', 'Aile']),
  TabuCard('Ayakkabı', ['Giymek', 'Ayak', 'Bağcık', 'Topuk', 'Çorap']),
  TabuCard('Saat', ['Zaman', 'Akrep', 'Yelkovan', 'Kol', 'Dakika']),
  TabuCard('Bahçe', ['Çiçek', 'Toprak', 'Ağaç', 'Ev', 'Çim']),
  TabuCard('Asker', ['Ordu', 'Silah', 'Vatan', 'Üniforma', 'Savaş']),
  TabuCard('Buzdolabı', ['Soğuk', 'Mutfak', 'Yemek', 'Dondurucu', 'Beyaz']),
  TabuCard('Yıldız', ['Gökyüzü', 'Gece', 'Parlak', 'Uzay', 'Işık']),
  TabuCard('Şemsiye', ['Yağmur', 'Açmak', 'Korumak', 'Sap', 'Islak']),
  TabuCard('Balık', ['Deniz', 'Su', 'Yüzmek', 'Solungaç', 'Olta']),
  TabuCard('Hediye', ['Paket', 'Doğum günü', 'Vermek', 'Sürpriz', 'Kurdele']),
  TabuCard('Köprü', ['Nehir', 'Geçmek', 'İki', 'Yol', 'Boğaz']),
  TabuCard('Polis', ['Suç', 'Hırsız', 'Üniforma', 'Güvenlik', 'Karakol']),
  TabuCard('Dondurma', ['Soğuk', 'Tatlı', 'Külah', 'Yaz', 'Çikolata']),
  TabuCard('Gözlük', ['Göz', 'Görmek', 'Cam', 'Numara', 'Güneş']),
  TabuCard('Tren', ['Ray', 'İstasyon', 'Vagon', 'Yolculuk', 'Lokomotif']),
  TabuCard('Çamaşır', ['Yıkamak', 'Makine', 'Kirli', 'Deterjan', 'Kurutmak']),
  TabuCard('Maymun', ['Hayvan', 'Muz', 'Ağaç', 'Tırmanmak', 'Orman']),
  TabuCard('Pencere', ['Cam', 'Açmak', 'Ev', 'Perde', 'Bakmak']),
  TabuCard('Doğum günü', ['Pasta', 'Mum', 'Yaş', 'Kutlama', 'Hediye']),
  TabuCard('Kalem', ['Yazmak', 'Kağıt', 'Uç', 'Defter', 'Silgi']),
  TabuCard('Anahtar', ['Kilit', 'Kapı', 'Açmak', 'Cep', 'Ev']),
  TabuCard('Bal', ['Arı', 'Tatlı', 'Petek', 'Sarı', 'Kahvaltı']),
  TabuCard('Kar', ['Soğuk', 'Beyaz', 'Kış', 'Yağmak', 'Kardan adam']),
];

const _sporCards = <TabuCard>[
  TabuCard('Basketbol', ['Pota', 'Top', 'Smaç', 'Saha', 'Ribaund']),
  TabuCard('Voleybol', ['File', 'Smaç', 'Top', 'Servis', 'Pas']),
  TabuCard('Hakem', ['Düdük', 'Maç', 'Kart', 'Karar', 'Faul']),
  TabuCard('Olimpiyat', ['Madalya', 'Ülke', 'Halka', 'Yarış', 'Dört yıl']),
  TabuCard('Şampiyon', ['Birinci', 'Kupa', 'Lig', 'Kazanmak', 'Final']),
  TabuCard('Kaleci', ['Kale', 'Eldiven', 'Top', 'Kurtarış', 'Gol']),
  TabuCard('Penaltı', ['Nokta', 'Vuruş', 'Kale', 'Faul', 'Ceza']),
  TabuCard('Antrenör', ['Takım', 'Çalıştırmak', 'Teknik', 'Kenar', 'Taktik']),
  TabuCard('Yüzme', ['Havuz', 'Su', 'Kulaç', 'Kosta', 'Olimpiyat']),
  TabuCard('Boks', ['Yumruk', 'Ring', 'Eldiven', 'Nakavt', 'Raunt']),
  TabuCard('Tenis', ['Raket', 'Kort', 'File', 'Top', 'Servis']),
  TabuCard('Forma', ['Tişört', 'Takım', 'Numara', 'Giymek', 'Renk']),
  TabuCard('Maraton', ['Koşmak', 'Uzun', 'Mesafe', 'Yarış', 'Kilometre']),
  TabuCard('Stadyum', ['Maç', 'Tribün', 'Saha', 'Seyirci', 'Futbol']),
  TabuCard('Gol', ['Kale', 'Ağ', 'Futbol', 'Atmak', 'Skor']),
  TabuCard('Kayak', ['Kar', 'Dağ', 'Pist', 'Kış', 'Kızak']),
  TabuCard('Bisiklet', ['Pedal', 'Tekerlek', 'Sürmek', 'Zincir', 'Yol']),
  TabuCard('Güreş', ['Minder', 'Pehlivan', 'Yağ', 'Kispet', 'Tutmak']),
  TabuCard('Satranç', ['Tahta', 'Şah', 'At', 'Piyon', 'Hamle']),
  TabuCard('Madalya', ['Altın', 'Gümüş', 'Bronz', 'Kazanmak', 'Boyun']),
  TabuCard('Tribün', ['Seyirci', 'Stat', 'Taraftar', 'Oturmak', 'Tezahürat']),
  TabuCard('Faul', ['Hakem', 'Kart', 'Düşmek', 'Ceza', 'Kural']),
  TabuCard('Raket', ['Tenis', 'Vurmak', 'Top', 'Sap', 'Masa']),
  TabuCard('Buz pateni', ['Buz', 'Kayma', 'Patika', 'Pist', 'Soğuk']),
  TabuCard('Lionel Messi', ['Futbol', 'Arjantin', 'Barcelona', 'Gol', 'Kısa']),
  TabuCard('Cristiano Ronaldo',
      ['Futbol', 'Portekiz', 'Gol', 'Real', 'Forma']),
  TabuCard('Rafael Nadal', ['Tenis', 'İspanyol', 'Toprak', 'Raket', 'Kort']),
  TabuCard('Roger Federer', ['Tenis', 'İsviçre', 'Raket', 'Zarif', 'Kort']),
  TabuCard('Novak Djokovic',
      ['Tenis', 'Sırbistan', 'Raket', 'Kort', 'Numara bir']),
  TabuCard('Michael Jordan', ['Basketbol', 'NBA', 'Amerikalı', 'Hava', 'Smaç']),
  TabuCard('LeBron James', ['Basketbol', 'NBA', 'Amerikalı', 'Lakers', 'Kral']),
  TabuCard('Usain Bolt', ['Koşu', 'Hızlı', 'Jamaika', 'Sprinter', 'Olimpiyat']),
  TabuCard('Muhammad Ali',
      ['Boks', 'Ring', 'Amerikalı', 'Kelebek', 'Şampiyon']),
  TabuCard('Mike Tyson', ['Boks', 'Yumruk', 'Kulak', 'Amerikalı', 'Nakavt']),
  TabuCard('Hidayet Türkoğlu',
      ['Basketbol', 'Türk', 'NBA', 'Uzun', 'Milli']),
  TabuCard('Naim Süleymanoğlu',
      ['Halter', 'Türk', 'Cep', 'Herkül', 'Olimpiyat']),
];

const _muzikCards = <TabuCard>[
  TabuCard('Gitar', ['Tel', 'Akor', 'Çalmak', 'Enstrüman', 'Mızrap']),
  TabuCard('Piyano', ['Tuş', 'Çalmak', 'Klavye', 'Nota', 'Akort']),
  TabuCard('Konser', ['Sahne', 'Bilet', 'Canlı', 'Dinleyici', 'Şarkıcı']),
  TabuCard('Şarkıcı', ['Söylemek', 'Mikrofon', 'Ses', 'Şarkı', 'Sahne']),
  TabuCard('Albüm', ['Şarkı', 'Kapak', 'Çıkmak', 'Plak', 'Liste']),
  TabuCard('Ritim', ['Tempo', 'Vuruş', 'Davul', 'Dans', 'Ahenk']),
  TabuCard('Davul', ['Vurmak', 'Baget', 'Ritim', 'Deri', 'Tokmak']),
  TabuCard('Mikrofon', ['Ses', 'Söylemek', 'Sahne', 'Şarkıcı', 'Kayıt']),
  TabuCard('Senfoni', ['Orkestra', 'Klasik', 'Beste', 'Şef', 'Salon']),
  TabuCard('Nota', ['Müzik', 'Do', 're', 'Porte', 'Yazmak']),
  TabuCard('Koro', ['Topluluk', 'Söylemek', 'Ses', 'Şef', 'Birlikte']),
  TabuCard('Saksofon', ['Üflemek', 'Caz', 'Pirinç', 'Enstrüman', 'Nefes']),
  TabuCard('Keman', ['Yay', 'Tel', 'Çalmak', 'Klasik', 'Çene']),
  TabuCard('Orkestra', ['Şef', 'Enstrüman', 'Senfoni', 'Topluluk', 'Sahne']),
  TabuCard('Melodi', ['Ezgi', 'Şarkı', 'Nota', 'Kulak', 'Akılda']),
  TabuCard('Plak', ['Dönmek', 'Eski', 'İğne', 'Albüm', 'Pikap']),
  TabuCard('Flüt', ['Üflemek', 'Delik', 'Nefes', 'İnce', 'Enstrüman']),
  TabuCard('Dansöz', ['Oyun', 'Göbek', 'Müzik', 'Sahne', 'Kıvırmak']),
  TabuCard('Rap', ['Söz', 'Ritim', 'Hızlı', 'Müzik', 'Kafiye']),
  TabuCard('Bando', ['Yürümek', 'Davul', 'Tören', 'Üflemeli', 'Takım']),
  TabuCard('Akor', ['Gitar', 'Nota', 'Basmak', 'Uyum', 'Tel']),
  TabuCard('Gam', ['Nota', 'Do re mi', 'Sıralama', 'Majör', 'Dizi']),
  TabuCard('Şef', ['Orkestra', 'Baton', 'Yönetmek', 'Koro', 'İşaret']),
  TabuCard('Klarnet', ['Üflemek', 'Nefes', 'Siyah', 'Enstrüman', 'Delik']),
  TabuCard('Hoparlör', ['Ses', 'Yüksek', 'Çıkmak', 'Bas', 'Cihaz']),
  TabuCard('Bruno Mars', ['Şarkıcı', 'Pop', 'Amerikalı', 'Funk', 'Uptown']),
  TabuCard('Justin Bieber', ['Kanadalı', 'Pop', 'Baby', 'Şarkıcı', 'Genç']),
  TabuCard('Sabrina Carpenter',
      ['Pop', 'Espresso', 'Şarkıcı', 'Amerikalı', 'Kadın']),
  TabuCard('Metallica', ['Metal', 'Grup', 'Rock', 'Gitar', 'Amerikan']),
  TabuCard('AC/DC', ['Rock', 'Grup', 'Avustralya', 'Gitar', 'Şimşek']),
  TabuCard('Queen', ['Grup', 'Rock', 'Freddie', 'Bohemian', 'İngiliz']),
  TabuCard('Michael Jackson',
      ['Pop', 'Kral', 'Moonwalk', 'Thriller', 'Dans']),
  TabuCard('The Beatles', ['Grup', 'İngiliz', 'Liverpool', 'Rock', 'Dörtlü']),
  TabuCard('Elvis Presley', ['Rock', 'Kral', 'Amerikalı', 'Eski', 'Şarkıcı']),
  TabuCard('Madonna', ['Pop', 'Kadın', 'Material', 'Amerikalı', 'Kraliçe']),
  TabuCard('Beyoncé', ['Pop', 'Kadın', 'Amerikalı', 'Destiny', 'Şarkıcı']),
  TabuCard('Taylor Swift', ['Pop', 'Kadın', 'Amerikalı', 'Country', 'Albüm']),
  TabuCard('Ed Sheeran', ['İngiliz', 'Kızıl', 'Gitar', 'Şarkıcı', 'Shape']),
  TabuCard('Eminem', ['Rap', 'Amerikalı', 'Beyaz', 'Slim', 'Detroit']),
  TabuCard('Adele', ['İngiliz', 'Kadın', 'Balad', 'Hello', 'Şarkıcı']),
  TabuCard('Rihanna', ['Pop', 'Kadın', 'Barbados', 'Umbrella', 'Şarkıcı']),
  TabuCard('Dua Lipa', ['Pop', 'İngiliz', 'Kadın', 'Levitating', 'Arnavut']),
  TabuCard('Billie Eilish', ['Pop', 'Genç', 'Amerikalı', 'Fısıltı', 'Kardeş']),
  TabuCard('Lady Gaga', ['Pop', 'Kadın', 'Poker', 'Amerikalı', 'Sıra dışı']),
  TabuCard('Shakira', ['Kolombiyalı', 'Kalça', 'Dans', 'Waka', 'Kadın']),
];

const _cografyaCards = <TabuCard>[
  TabuCard('İstanbul', ['Boğaz', 'Köprü', 'Şehir', 'Türkiye', 'Marmara']),
  TabuCard('Ankara', ['Başkent', 'Türkiye', 'Şehir', 'Anıtkabir', 'İç Anadolu']),
  TabuCard('Nehir', ['Su', 'Akmak', 'Deniz', 'Yatak', 'Kıyı']),
  TabuCard('Dağ', ['Yüksek', 'Zirve', 'Tırmanmak', 'Tepe', 'Kar']),
  TabuCard('Çöl', ['Kum', 'Sıcak', 'Susuz', 'Sahra', 'Deve']),
  TabuCard('Ada', ['Deniz', 'Etraf', 'Su', 'Kara', 'Kıbrıs']),
  TabuCard('Volkan', ['Lav', 'Patlamak', 'Dağ', 'Magma', 'Krater']),
  TabuCard('Okyanus', ['Deniz', 'Büyük', 'Su', 'Atlas', 'Pasifik']),
  TabuCard('Başkent', ['Şehir', 'Yönetim', 'Ankara', 'Ülke', 'Merkez']),
  TabuCard('Kıta', ['Asya', 'Avrupa', 'Kara', 'Büyük', 'Afrika']),
  TabuCard('Göl', ['Su', 'Tatlı', 'Van', 'Kıyı', 'Tuz']),
  TabuCard('Ekvator', ['Çizgi', 'Sıcak', 'Dünya', 'Orta', 'Enlem']),
  TabuCard('Harita', ['Yön', 'Ülke', 'Çizmek', 'Pusula', 'Atlas']),
  TabuCard('Deprem', ['Sarsıntı', 'Fay', 'Yer', 'Şiddet', 'Richter']),
  TabuCard('Boğaz', ['Deniz', 'İstanbul', 'Geçit', 'Köprü', 'Su']),
  TabuCard('Vadi', ['Dağ', 'Çukur', 'Arası', 'Nehir', 'Derin']),
  TabuCard('Kıyı', ['Deniz', 'Sahil', 'Kara', 'Su', 'Kenar']),
  TabuCard('Yarımada', ['Kara', 'Deniz', 'Üç', 'Anadolu', 'Çıkıntı']),
  TabuCard('İklim', ['Hava', 'Sıcaklık', 'Yağış', 'Mevsim', 'Bölge']),
  TabuCard('Kutup', ['Soğuk', 'Buz', 'Kuzey', 'Güney', 'Penguen']),
  TabuCard('Pamukkale', ['Beyaz', 'Travarten', 'Denizli', 'Termal', 'Teras']),
  TabuCard('Kapadokya', ['Balon', 'Peri', 'Bacası', 'Nevşehir', 'Mağara']),
  TabuCard('Pusula', ['Yön', 'Kuzey', 'İğne', 'Manyetik', 'Harita']),
  TabuCard('Şelale', ['Su', 'Yükseklik', 'Dökülmek', 'Nehir', 'Düşmek']),
];

const _basitCards = <TabuCard>[
  TabuCard('Top', ['Yuvarlak', 'Oynamak', 'Zıplamak', 'Futbol', 'Atmak']),
  TabuCard('Su', ['İçmek', 'Şeffaf', 'Bardak', 'Islak', 'Musluk']),
  TabuCard('Ev', ['Yaşamak', 'Oturmak', 'Kapı', 'Çatı', 'Oda']),
  TabuCard('El', ['Parmak', 'Tutmak', 'Kol', 'Beş', 'Avuç']),
  TabuCard('Köpek', ['Havlamak', 'Hayvan', 'Kuyruk', 'Evcil', 'Pati']),
  TabuCard('Elma', ['Meyve', 'Kırmızı', 'Yemek', 'Ağaç', 'Yeşil']),
  TabuCard('Kapı', ['Açmak', 'Kapamak', 'Ev', 'Kol', 'Giriş']),
  TabuCard('Masa', ['Oturmak', 'Sandalye', 'Üstü', 'Ayak', 'Yemek']),
  TabuCard('Süt', ['İçmek', 'Beyaz', 'İnek', 'Bardak', 'Kahvaltı']),
  TabuCard('Bebek', ['Küçük', 'Ağlamak', 'Anne', 'Emzik', 'Beşik']),
  TabuCard('Çiçek', ['Bahçe', 'Renk', 'Koklamak', 'Yaprak', 'Açmak']),
  TabuCard('Ayak', ['Yürümek', 'Bacak', 'Parmak', 'Ayakkabı', 'Adım']),
  TabuCard('Kaşık', ['Çorba', 'Yemek', 'Sap', 'Çatal', 'Mutfak']),
  TabuCard('Yatak', ['Uyumak', 'Oda', 'Yorgan', 'Yastık', 'Uzanmak']),
  TabuCard('Burun', ['Koklamak', 'Yüz', 'Nefes', 'Orta', 'Mendil']),
  TabuCard('Ekmek', ['Fırın', 'Yemek', 'Dilim', 'Buğday', 'Bayat']),
  TabuCard('Göz', ['Görmek', 'Bakmak', 'Yüz', 'Kirpik', 'İki']),
  TabuCard('Balon', ['Şişirmek', 'Hava', 'Uçmak', 'Patlamak', 'Renkli']),
  TabuCard('Kuş', ['Uçmak', 'Kanat', 'Tüy', 'Yuva', 'Ötmek']),
  TabuCard('Saç', ['Baş', 'Tarak', 'Kesmek', 'Uzun', 'Renk']),
  TabuCard('Sandalye', ['Oturmak', 'Masa', 'Ayak', 'Arkalık', 'Tahta']),
  TabuCard('Diş', ['Fırça', 'Ağız', 'Beyaz', 'Macun', 'Isırmak']),
  TabuCard('Mum', ['Yakmak', 'Işık', 'Eritmek', 'Doğum günü', 'Alev']),
  TabuCard('Saat', ['Zaman', 'Kol', 'Akrep', 'Tik tak', 'Dakika']),
];

const _edebiyatCards = <TabuCard>[
  TabuCard('Roman', ['Kitap', 'Yazar', 'Hikaye', 'Sayfa', 'Kurgu']),
  TabuCard('Şiir', ['Mısra', 'Kafiye', 'Şair', 'Dize', 'Ahenk']),
  TabuCard('Şair', ['Şiir', 'Yazmak', 'Mısra', 'Kafiye', 'Divan']),
  TabuCard('Hikaye', ['Kısa', 'Anlatı', 'Olay', 'Yazar', 'Masal']),
  TabuCard('Masal', ['Çocuk', 'Prenses', 'Anlatmak', 'Cadı', 'Bir varmış']),
  TabuCard('Tiyatro', ['Sahne', 'Oyun', 'Perde', 'Oyuncu', 'Replik']),
  TabuCard('Yazar', ['Kitap', 'Roman', 'Kalem', 'Eser', 'Yazmak']),
  TabuCard('Destan', ['Kahraman', 'Eski', 'Uzun', 'Anlatı', 'Manas']),
  TabuCard('Atasözü', ['Söz', 'Halk', 'Öğüt', 'Kısa', 'Anlam']),
  TabuCard('Kafiye', ['Uyak', 'Şiir', 'Ses', 'Son', 'Benzemek']),
  TabuCard('Deneme', ['Yazı', 'Düşünce', 'Konu', 'Montaigne', 'Anlatım']),
  TabuCard('Roman kahramanı',
      ['Karakter', 'Kitap', 'Başrol', 'Kişi', 'Hikaye']),
  TabuCard('Divan', ['Osmanlı', 'Şiir', 'Gazel', 'Eski', 'Şair']),
  TabuCard('Gazel', ['Divan', 'Şiir', 'Aşk', 'Beyit', 'Osmanlı']),
  TabuCard('Nazım', ['Hikmet', 'Şair', 'Memleket', 'Şiir', 'Mahkum']),
  TabuCard('Sait Faik', ['Öykü', 'Yazar', 'Ada', 'Hikaye', 'Burgazada']),
  TabuCard('Yaşar Kemal', ['İnce Memed', 'Roman', 'Çukurova', 'Yazar', 'Köy']),
  TabuCard('Metafor', ['Benzetme', 'Mecaz', 'Anlam', 'Söz', 'Edebi']),
  TabuCard('Kütüphane', ['Kitap', 'Raf', 'Okumak', 'Sessiz', 'Ödünç']),
  TabuCard('Beyit', ['İki', 'Dize', 'Şiir', 'Mısra', 'Divan']),
  TabuCard('Fabl', ['Hayvan', 'Ders', 'Kısa', 'Öğüt', 'La Fontaine']),
  TabuCard('Klasik', ['Eski', 'Eser', 'Değerli', 'Kalıcı', 'Başyapıt']),
  TabuCard('Anı', ['Hatıra', 'Geçmiş', 'Yazmak', 'Yaşanmış', 'Hatırlamak']),
  TabuCard('Çeviri', ['Dil', 'Çevirmen', 'Aktarmak', 'Yabancı', 'Metin']),
];

const _unlulerCards = <TabuCard>[
  TabuCard('Atatürk', ['Cumhuriyet', 'Kurtuluş', 'Türkiye', 'Lider', 'Samsun']),
  TabuCard('Albert Einstein', ['Bilim', 'İzafiyet', 'Fizik', 'Saç', 'Dahi']),
  TabuCard('Cristiano Ronaldo',
      ['Futbol', 'Portekiz', 'Gol', 'Real', 'Forma']),
  TabuCard('Lionel Messi', ['Futbol', 'Arjantin', 'Barcelona', 'Gol', 'Kısa']),
  TabuCard('Cem Yılmaz', ['Komedyen', 'Türk', 'Film', 'Stand-up', 'Gülmek']),
  TabuCard('Kıvanç Tatlıtuğ',
      ['Oyuncu', 'Dizi', 'Yakışıklı', 'Türk', 'Model']),
  TabuCard('Brad Pitt', ['Oyuncu', 'Hollywood', 'Film', 'Amerikalı', 'Yakışıklı']),
  TabuCard('Angelina Jolie', ['Oyuncu', 'Hollywood', 'Kadın', 'Film', 'Dudak']),
  TabuCard('Leonardo DiCaprio',
      ['Oyuncu', 'Titanic', 'Hollywood', 'Oscar', 'Film']),
  TabuCard('Elon Musk', ['Tesla', 'Zengin', 'Uzay', 'Milyarder', 'Roket']),
  TabuCard('Bill Gates', ['Microsoft', 'Zengin', 'Bilgisayar', 'Milyarder', 'Yazılım']),
  TabuCard('Steve Jobs', ['Apple', 'iPhone', 'Bilgisayar', 'Telefon', 'Kurucu']),
  TabuCard('Charlie Chaplin', ['Sessiz', 'Komedi', 'Bıyık', 'Şapka', 'Baston']),
  TabuCard('Isaac Newton', ['Yerçekimi', 'Elma', 'Bilim', 'Fizik', 'Yasa']),
  TabuCard('Picasso', ['Ressam', 'Resim', 'Sanat', 'İspanyol', 'Tablo']),
  TabuCard('Napolyon', ['Fransız', 'İmparator', 'Komutan', 'Kısa', 'Savaş']),
  TabuCard('Marie Curie', ['Bilim', 'Kadın', 'Radyasyon', 'Nobel', 'Fizik']),
  TabuCard('Mevlana', ['Şair', 'Konya', 'Sema', 'Mesnevi', 'Tasavvuf']),
  TabuCard('Fatih Sultan Mehmet',
      ['Padişah', 'İstanbul', 'Fetih', 'Osmanlı', '1453']),
  TabuCard('Nasreddin Hoca', ['Fıkra', 'Eşek', 'Göl', 'Komik', 'Akşehir']),
  TabuCard('Michael Jordan', ['Basketbol', 'NBA', 'Amerikalı', 'Hava', 'Smaç']),
  TabuCard('Usain Bolt', ['Koşu', 'Hızlı', 'Jamaika', 'Olimpiyat', 'Sprinter']),
  TabuCard('Shakespeare', ['Yazar', 'Tiyatro', 'İngiliz', 'Hamlet', 'Oyun']),
  TabuCard('Aziz Sancar', ['Bilim', 'Nobel', 'Türk', 'DNA', 'Kimya']),
];
